### ISSUE TITLE
Olympus login fails on https 

### ISSUE THREAD

**Issue by otsakir** [Mobicents/olympus#13] opened 2015-10-29 15:16 UTC
The error occurs when trying to login Olympus over https. Both self-signed and official certificates were used but the behaviour didn't change.

```
PrivateJainSipClientConnector:open(): catched exception:SecurityError: The operation is insecure. WebRTComm.js:1405:9

			Error: The operation is insecure.
			WSMessageChannel.prototype.createWebSocket@https://instance1.restcomm.com:8443/olympus/resources/js/mobicents-libs/jain-sip.js:25448:20
			WSMessageChannel@https://instance1.restcomm.com:8443/olympus/resources/js/mobicents-libs/jain-sip.js:25439:20
			WSMessageProcessor@https://instance1.restcomm.com:8443/olympus/resources/js/mobicents-libs/jain-sip.js:25659:27
			SipStackImpl.prototype.createListeningPoint@https://instance1.restcomm.com:8443/olympus/resources/js/mobicents-libs/jain-sip.js:31692:28
			PrivateJainSipClientConnector.prototype.open@https://instance1.restcomm.com:8443/olympus/resources/js/mobicents-libs/WebRTComm.js:1353:50
			WebRTCommClient.prototype.open@https://instance1.restcomm.com:8443/olympus/resources/js/mobicents-libs/WebRTComm.js:4982:21
			$scope.connect@https://instance1.restcomm.com:8443/olympus/resources/js/controllers/register.js:120:5
			$parseFunctionCall@https://instance1.restcomm.com:8443/olympus/lib/angular/angular.js:12336:15
			ngEventHandler/</callback@https://instance1.restcomm.com:8443/olympus/lib/angular/angular.js:21422:17
			$RootScopeProvider/this.$get</Scope.prototype.$eval@https://instance1.restcomm.com:8443/olympus/lib/angular/angular.js:14388:16
			$RootScopeProvider/this.$get</Scope.prototype.$apply@https://instance1.restcomm.com:8443/olympus/lib/angular/angular.js:14487:18
			ngEventHandler/<@https://instance1.restcomm.com:8443/olympus/lib/angular/angular.js:21427:17
			jQuery.event.dispatch@https://instance1.restcomm.com:8443/olympus/lib/jquery/dist/jquery.js:4429:15
			jQuery.event.add/elemData.handle@https://instance1.restcomm.com:8443/olympus/lib/jquery/dist/jquery.js:4116:6
```

**Comment by deruelle** [comment] 2015-11-09 17:33
This is what we use in Docker Image when using secure only Restcomm : 
sed -i "s|ws:|wss:|" $BASEDIR/standalone/deployments/olympus.war/resources/js/controllers/register.js

**Comment by deruelle** [comment] 2015-11-09 17:34
Maybe it would be good to add an option like a lock to connect over a secure wss protocol instead of ws as well as to allow to use a different port like 5083 or 5063 by default ?

**Comment by KietnaQuTak** [comment] 2015-12-04 15:00
Hello. I have just stumbled upon "WSMessageChannel:createWebSocket(): websocket connection has failed:[object Event]" error after updating to stable version of Google Chrome (same in v48 beta) and as far as I understand it's a new standard that Google is pushing permanently.

When committed latest version of JAIN SIP You have written "now need the UI to be able to define it as well". I'm using Olympus downloaded 2-3 weeks ago, does it have mention updates? Should I change anything in code to force wss permanently or should it run by default?

Best regards
Kietna Qu'Tak

**Comment by deruelle** [comment] 2015-12-04 16:15
see comments above, you need to replace in the code all ws: by wss: olympus.war/resources/js/controllers/register.js

**Comment by KietnaQuTak** [comment] 2015-12-07 14:12
Thanks Deruelle for answer.

How about any server side changes? I'm running stand alone version of Restcomm, so should I do anything to connect Olympus and Restcomm over WSS?

**Comment by deruelle** [comment] 2015-12-08 02:33
If you use RestComm on the server side, yes. 
Please follow the steps from http://docs.telestax.com/restcomm-enable-https-secure-connector-on-jboss-as-7-or-eap-6/

**Comment by KietnaQuTak** [comment] 2015-12-08 10:07
Thanks again for response. Rescomm goes with SSL (under https) with self-signed certificate. It is available and web interface works well. Nevertheless we have issues with wss connector. We have configured our jboss to use wss in place of ws (on the same port). In the jboss start log we can see, that it seems to be started (10:56:33,729 INFO [org.mobicents.servlet.sip.catalina.SipProtocolHandler] (MSC service thread 1-2) Sip Connector started on ip address: 172.20.0.222, port 5082, transport wss, useStun false, stunAddress null, stunPort : -1, useStaticAddress: true, staticServerAddress 172.20.0.222, staticServerPort 5082).

In olympus.war we changed ws: to wss: in order to connect via secure channel.

When we test it - we can see in js console, that the seocket is not available: WebSocket connection to 'wss://172.20.0.222:5082/' failed: Error in connection establishment: net::ERR_CONNECTION_CLOSED jain-sip.js:25466 WSMessageChannel:createWebSocket(): websocket connection has failed:[object Event]websocket.onerror @ jain-sip.js:25466 WebRTComm.js:1774 PrivateJainSipClientConnector:processConnectionError(): SIP connection has failed, error:[object Event]

There no logs on restcomm’s side.

**Comment by atsakiridis** [comment] 2015-12-08 19:05
I think you also need to update jain configuration to use the same cert you created for RestComm

Edit $RESTCOMM/standalone/configuration/mss-sip-stack.properties and add in the end (update the path to the keystore with yours:

        gov.nist.javax.sip.TLS_CLIENT_AUTH_TYPE=Disabled
        javax.net.ssl.keyStore=/home/antonis/staging/Mobicents-Restcomm-JBoss-AS7-7.4.0.746/standalone/configuration/restcomm.keystore
        javax.net.ssl.keyStorePassword=<password>
        javax.net.ssl.trustStorePassword=<password>
        javax.net.ssl.trustStore=/home/antonis/staging/Mobicents-Restcomm-JBoss-AS7-7.4.0.746/standalone/configuration/restcomm.keystore
        javax.net.ssl.keyStoreType=JKS

That should do it

**Comment by brainslog** [comment] 2015-12-08 23:32
Fixed the WS protocol to adapt depending on Olympus running on https or http, with https://github.com/Mobicents/olympus/commit/1d8d9d275ef8c00c3e85b690e1b1af7cad5c1422.

**Comment by deruelle** [comment] 2015-12-09 03:01
new build available containing the fix at https://mobicents.ci.cloudbees.com/job/Olympus/lastSuccessfulBuild/artifact/target/

**Comment by KietnaQuTak** [comment] 2015-12-11 13:40
Thanks for quick fix, it works for us, but after changes we have problem with MediaServer. It looks like there is an issue with DTLS Handshake.

2015-12-11 14:23:41,853 ERROR [DtlsHandler] (Thread-9) DTLS handshake failed: internal_error(80)
org.bouncycastle.crypto.tls.TlsFatalAlert: internal_error(80)
       at org.bouncycastle.crypto.tls.DTLSServerProtocol.accept(Unknown Source)
       at org.mobicents.media.server.impl.srtp.DtlsHandler$HandshakeWorker.run(DtlsHandler.java:343)
       at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: Handshake is taking too long! (>10000ms
       at org.mobicents.media.server.impl.srtp.NioUdpTransport.receive(NioUdpTransport.java:94)
       at org.bouncycastle.crypto.tls.DTLSRecordLayer.receiveRecord(Unknown Source)
       at org.bouncycastle.crypto.tls.DTLSRecordLayer.receive(Unknown Source)
       at org.bouncycastle.crypto.tls.DTLSReliableHandshake.receiveMessage(Unknown Source)
       at org.bouncycastle.crypto.tls.DTLSServerProtocol.serverHandshake(Unknown Source)
       ... 3 more

During those 4 seconds we got 100% CPU load with RestComm server process. In described scenario the call is between WebRTC client and external sip server via trunk. We were trying to extend timeout to 10 seconds (in code) with no changes.

BTW: In above fix I think that there is a mistake with second port 5082 which is ok for our case but may not be best case for general release since Deruelle suggest using different ports for ws and wss.

**Comment by deruelle** [comment] 2015-12-11 15:36
Can you open a separate issue on https://github.com/Mobicents/mediaserver for this one ?
Thanks Closing this ticket.

**Closed by deruelle** 2015-12-11 15:36 UTC
Labels: bug
